/**
 * Generated by Orval 0.1.0 for Zod Schemas 🍺
 * Do not edit manually. Regenerate with "pnpm generate:api-client".
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from "zod";

/**
 * @summary Root
 */
export const rootResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Hello World
 */
export const helloWorldResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Create User
 */
export const createUserBody = zod.object({
  name: zod.string(),
  email: zod.string(),
});

export const createUserResponse = zod.object({
  message: zod.string(),
});
