/**
 * Generated by Orval 0.1.0 for Zod Schemas 🍺
 * Do not edit manually. Regenerate with "pnpm generate:api-client".
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { User } from "../../model";

import { customInstance } from "../../lib/axiosInstance";

/**
 * @summary Root
 */
export const root = () => {
  return customInstance<unknown>({ url: `/`, method: "GET" });
};
/**
 * @summary Hello World
 */
export const helloWorld = () => {
  return customInstance<unknown>({ url: `/hello`, method: "GET" });
};
/**
 * @summary Create User
 */
export const createUser = (user: User) => {
  return customInstance<unknown>({
    url: `/users`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: user,
  });
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;
