"""allow null opposing name

Revision ID: 01e6a343ead0
Revises: cc8021ddd806
Create Date: 2025-06-12 15:34:18.533121

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '01e6a343ead0'
down_revision: str | None = 'cc8021ddd806'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'opposing_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'opposing_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
