"""fix usagetype enum

Revision ID: 1e494eb57ce2
Revises: c752da0515ee
Create Date: 2025-06-18 18:48:47.537282

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1e494eb57ce2'
down_revision: str | None = 'c752da0515ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE usagetype RENAME VALUE 'PERSONAL' TO 'PRIV'")
    op.execute("ALTER TYPE usagetype RENAME VALUE 'BUSINESS' TO 'ORGA'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE usagetype RENAME VALUE 'PRIV' TO 'PERSONAL'")
    op.execute("ALTER TYPE usagetype RENAME VALUE 'ORGA' TO 'BUSINESS'")
    # ### end Alembic commands ###
