"""remove unique from account name

Revision ID: 20960f21b210
Revises: 7f8c94e42aa7
Create Date: 2025-06-08 21:34:45.141520

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '20960f21b210'
down_revision: str | None = '7f8c94e42aa7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_name_key', 'account', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('account_name_key', 'account', ['name'])
    # ### end Alembic commands ###
