"""add indexes

Revision ID: 22566866436d
Revises: f85d15a7d52a
Create Date: 2025-06-22 01:13:17.293808

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '22566866436d'
down_revision: str | None = 'f85d15a7d52a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_account_bban'), 'account', ['bban'], unique=False)
    op.create_index(op.f('ix_account_connection_id'), 'account', ['connection_id'], unique=False)
    op.create_index(op.f('ix_account_iban'), 'account', ['iban'], unique=False)
    op.create_index(op.f('ix_connection_internal_id'), 'connection', ['internal_id'], unique=False)
    op.create_index(op.f('ix_connection_user_id'), 'connection', ['user_id'], unique=False)
    op.create_index(op.f('ix_counterparty_bban'), 'counterparty', ['bban'], unique=False)
    op.create_index(op.f('ix_counterparty_creator_id'), 'counterparty', ['creator_id'], unique=False)
    op.create_index(op.f('ix_counterparty_iban'), 'counterparty', ['iban'], unique=False)
    op.create_index(op.f('ix_transaction_account_id'), 'transaction', ['account_id'], unique=False)
    op.create_index('ix_transaction_account_processing_status', 'transaction', ['account_id', 'processing_status'], unique=False)
    op.create_index(op.f('ix_transaction_booking_time'), 'transaction', ['booking_time'], unique=False)
    op.create_index(op.f('ix_transaction_processing_status'), 'transaction', ['processing_status'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_transaction_processing_status'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_booking_time'), table_name='transaction')
    op.drop_index('ix_transaction_account_processing_status', table_name='transaction')
    op.drop_index(op.f('ix_transaction_account_id'), table_name='transaction')
    op.drop_index(op.f('ix_counterparty_iban'), table_name='counterparty')
    op.drop_index(op.f('ix_counterparty_creator_id'), table_name='counterparty')
    op.drop_index(op.f('ix_counterparty_bban'), table_name='counterparty')
    op.drop_index(op.f('ix_connection_user_id'), table_name='connection')
    op.drop_index(op.f('ix_connection_internal_id'), table_name='connection')
    op.drop_index(op.f('ix_account_iban'), table_name='account')
    op.drop_index(op.f('ix_account_connection_id'), table_name='account')
    op.drop_index(op.f('ix_account_bban'), table_name='account')
    # ### end Alembic commands ###
