"""add connection model

Revision ID: 7f8c94e42aa7
Revises: d416a1e383f5
Create Date: 2025-06-02 16:15:59.570216

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7f8c94e42aa7'
down_revision: str | None = 'd416a1e383f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_type', sa.Enum('MANUAL', 'GOCARDLESS', name='connectiontype'), nullable=False),
    sa.Column('internal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('account', sa.Column('connection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('account_user_id_fkey', 'account', type_='foreignkey')
    op.create_foreign_key('account_connection_id_fkey', 'account', 'connection', ['connection_id'], ['id'])
    op.drop_column('account', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('account_connection_id_fkey', 'account', type_='foreignkey')
    op.create_foreign_key('account_user_id_fkey', 'account', 'user', ['user_id'], ['id'])
    op.drop_column('account', 'connection_id')
    op.drop_table('connection')
    op.execute('DROP TYPE connectiontype;')
    # ### end Alembic commands ###
