"""use internal id as unique index in account

Revision ID: 8dd142df6766
Revises: 1e494eb57ce2
Create Date: 2025-06-19 13:30:19.602814

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8dd142df6766'
down_revision: str | None = '1e494eb57ce2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_unique_identifiers', table_name='account')
    op.create_unique_constraint('uq_account_internal_id', 'account', ['internal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_internal_id', 'account', type_='unique')
    op.create_index('ix_account_unique_identifiers', 'account', [sa.literal_column("COALESCE(iban, ''::character varying)"), sa.literal_column("COALESCE(bban, ''::character varying)"), sa.literal_column("COALESCE(bic, ''::character varying)"), sa.literal_column("COALESCE(scan_code, ''::character varying)")], unique=True)
    # ### end Alembic commands ###
