"""update transaction indexes

Revision ID: cc8021ddd806
Revises: f537b94200d3
Create Date: 2025-06-12 15:25:29.088534

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cc8021ddd806'
down_revision: str | None = 'f537b94200d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'gocardless_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('transaction_gocardless_id_key', 'transaction', type_='unique')
    op.create_index('ix_transaction_unique_identifiers', 'transaction', [sa.literal_column("coalesce(gocardless_id, '')"), sa.literal_column("coalesce(internal_id, '')")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_unique_identifiers', table_name='transaction')
    op.create_unique_constraint('transaction_gocardless_id_key', 'transaction', ['gocardless_id'])
    op.alter_column('transaction', 'gocardless_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
