// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
  detail?: Array<ValidationError>;
};

export type MessageResponse = {
  message: string;
};

export type User = {
  name: string;
  email: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type RootData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type RootResponse = RootResponses[keyof RootResponses];

export type HelloWorldData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/hello";
};

export type HelloWorldResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type HelloWorldResponse = HelloWorldResponses[keyof HelloWorldResponses];

export type PingData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type CreateUserData = {
  body: User;
  path?: never;
  query?: never;
  url: "/users";
};

export type CreateUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
