// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zValidationError = z.object({
  loc: z.array(z.unknown()),
  msg: z.string(),
  type: z.string(),
});

export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

export const zMessageResponse = z.object({
  message: z.string(),
});

export const zUser = z.object({
  name: z.string(),
  email: z.string(),
});

export const zRootResponse = zMessageResponse;

export const zHelloWorldResponse = zMessageResponse;

export const zPingResponse = zMessageResponse;

export const zCreateUserResponse = zMessageResponse;
