// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zBodyPasswordLogin = z.object({
  grant_type: z.union([z.string().regex(/^password$/), z.null()]).optional(),
  username: z.string(),
  password: z.string(),
  scope: z.string().optional().default(""),
  client_id: z.union([z.string(), z.null()]).optional(),
  client_secret: z.union([z.string(), z.null()]).optional(),
});

export const zErrorResponse = z.object({
  detail: z.string(),
});

export const zValidationError = z.object({
  loc: z.array(z.unknown()),
  msg: z.string(),
  type: z.string(),
});

export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

export const zMessageResponse = z.object({
  message: z.string(),
});

export const zToken = z.object({
  access_token: z.string(),
});

export const zUser = z.object({
  name: z.string(),
  email: z.string(),
});

export const zUserCreate = z.object({
  first_name: z.string(),
  last_name: z.string(),
  email: z.string(),
  password: z.string(),
});

export const zPasswordLoginResponse = zToken;

export const zRegisterResponse = zToken;

export const zRefreshTokenResponse = zToken;

export const zLogoutResponse = zMessageResponse;

export const zRootResponse = zMessageResponse;

export const zHelloWorldResponse = zMessageResponse;

export const zPingResponse = zMessageResponse;

export const zCreateUserResponse = zMessageResponse;
