/**
 * Generated by Orval 0.1.0 for Zod Schemas 🍺
 * Do not edit manually. Regenerate with "pnpm generate:api-client".
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationError } from "./validationError";

export interface HTTPValidationError {
  detail?: ValidationError[];
}
